export const ADMIN_CREATENODE = "ADMIN_CREATENODE"
export const ADMIN_OPENCREATE = "ADMIN_OPENCREATE"
export const ADMIN_CREATEDCOMPLETE = "ADMIN_CREATEDCOMPLETE"

export const ADMIN_DELETENODE = "ADMIN_DELETENODE"

export const ADMIN_ADDCONNECTION = "ADMIN_ADDCONNECTION"
export const ADMIN_ADDVIDEO= "ADMIN_ADDVIDEO"
export const ADMIN_ADDARTICLE = "ADMIN_ADDARTICLE"
export const ADMIN_ADDDESCRIPTION = "ADMIN_ADDDESCRIPTION"

export const SELECT_NODE = "SELECT_NODE"
export const REGISTER_CY = "REGISTER_CY"

export const CLOSE_USER_VIEW = "CLOSE_USER_VIEW"
export const USER_OPEN_MODULE = "USER_OPEN_MODULE"
export const USER_CLOSE_MODULE = "USER_CLOSE_MODULE"
export const ADMIN_OPEN_VIEW = "ADMIN_OPEN_VIEW"
export const ADMIN_CLOSE_VIEW = "ADMIN_CLOSE_VIEW"