export const ADMIN_CREATENODE = "ADMIN_CREATENODE"
export const ADMIN_OPENCREATE = "ADMIN_OPENCREATE"
export const ADMIN_CREATEDCOMPLETE = "ADMIN_CREATEDCOMPLETE"
export const ADMIN_CREATE_EDGES = 'ADMIN_CREATE_EDGES'

export const ADMIN_EDITNODE = "ADMIN_EDITNODE"
export const ADMIN_OPEN_EDIT = "ADMIN_OPEN_EDIT"
export const ADMIN_CLOSE_EDIT = "ADMIN_CLOSE_EDIT"
export const TOGGLE_ADMIN = "TOGGLE_ADMIN"

export const ADMIN_OPEN_ADDVIDEO = "ADMIN_OPEN_ADDVIDEO"
export const ADMIN_CLOSE_ADDVIDEO = "ADMIN_CLOSE_ADDVIDEO"
export const ADMIN_OPEN_ADDARTICLE = "ADMIN_OPEN_ADDARTICLE"
export const ADMIN_CLOSE_ADDARTICLE = "ADMIN_CLOSE_ADDARTICLE"

export const ADMIN_DELETENODE = "ADMIN_DELETENODE"

export const ADMIN_ADDCONNECTION = "ADMIN_ADDCONNECTION"
export const ADMIN_ADDVIDEO= "ADMIN_ADDVIDEO"
export const ADMIN_ADDARTICLE = "ADMIN_ADDARTICLE"
export const ADMIN_ADDDESCRIPTION = "ADMIN_ADDDESCRIPTION"

export const SELECT_NODE = "SELECT_NODE"
export const REGISTER_CY = "REGISTER_CY"
export const FETCH_NODES = 'FETCH_NODES'


export const CLOSE_USER_VIEW = "CLOSE_USER_VIEW"
export const USER_OPEN_MODULE = "USER_OPEN_MODULE"
export const USER_CLOSE_MODULE = "USER_CLOSE_MODULE"
export const ADMIN_OPEN_VIEW = "ADMIN_OPEN_VIEW"
export const ADMIN_CLOSE_VIEW = "ADMIN_CLOSE_VIEW"