export const ADMIN_CREATENODE = "ADMIN_CREATENODE"
export const ADMIN_DELETENODE = "ADMIN_DELETENODE"

export const ADMIN_ADDCONNECTION = "ADMIN_ADDCONNECTION"
export const ADMIN_ADDVIDEO= "ADMIN_ADDVIDEO"
export const ADMIN_ADDARTICLE = "ADMIN_ADDARTICLE"
export const ADMIN_ADDDESCRIPTION = "ADMIN_ADDDESCRIPTION"

export const SELECT_NODE = "SELECT_NODE"
export const REGISTER_CY = "REGISTER_CY"